---
title: "ts_test"
author: "Christopher Chan"
date: "February 7, 2019"
output:
    github_document
---


https://rpubs.com/hrbrmstr/time-series-machinations
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(chron)
library(zoo)
library(xts)
```

Reading in a logger dataset that I've been using for testing.
```{r, results='hide', message=FALSE}
here()

lv <- read_csv('180301 Level Data.csv')


lv$date_time <- as.POSIXct(lv$date_time, format = '%m/%d/%y %H:%M')
# lv$date_time <- format(lv$date_time, format = '%Y-%m-%d %H:%M')
str(lv)
```

Constructing the zoo class for our data. We are just starting out with water level.
```{r}
lv_zoo <- zoo(lv$level_m, order.by = lv$date_time)

str(lv_zoo)
```

Checking to make sure all the data points are in the zoo class. 
```{r}
start(lv_zoo)
end(lv_zoo)
```

https://datascienceplus.com/time-series-analysis-using-arima-model-in-r/

Fitting an arima model to the data
```{r}

```

```{r}
lv_zoo <- data.frame(lv_zoo)

lv_zoo$ts <- as.POSIXct(rownames(lv_zoo), format = "%Y-%m-%d %H:%M:%S")


head(lv_zoo)

ggplot(lv_zoo, aes(ts, lv_zoo)) +
    geom_line()

```

```{r}
ggplot(lv, aes(date_time, level_m)) +
    geom_line()
```











